version: "3.8"

services:
  # Database - Mongo DB
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    ports:
      - "$MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT"
    volumes:
      - ./db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  auth:
    container_name: auth
    depends_on:
      - mongodb
    build: ./auth
    command: npm run debug
    x-develop:
      watch:
        - action: sync
          path: ./auth
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./auth/package.json
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - 9229:9229
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./auth/app:/usr/src/app/app
volumes:
  db:
